const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Behaviors.MoveTo,
		C3.Plugins.TextBox,
		C3.Plugins.Massive_Cube_Rex_CSV2Array,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Text.Cnds.CompareText
	];
};
self.C3_JsPropNameTable = [
	{bg: 0},
	{ScrollTo: 0},
	{Anchor: 0},
	{Closer: 0},
	{Text: 0},
	{question: 0},
	{TiledBackground: 0},
	{two: 0},
	{company: 0},
	{love: 0},
	{forUs: 0},
	{avanture: 0},
	{sex: 0},
	{Touch: 0},
	{MoveTo: 0},
	{camera: 0},
	{TiledBackground2: 0},
	{move: 0},
	{sizee: 0},
	{game: 0},
	{settings: 0},
	{info: 0},
	{version2: 0},
	{TextInput: 0},
	{CSVToArray: 0},
	{AJAX: 0},
	{twoArray: 0},
	{Browser: 0},
	{miss: 0},
	{complite: 0},
	{reans: 0},
	{home: 0},
	{JSON: 0},
	{cardBg: 0},
	{numberQuestion: 0},
	{Fade: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{buttons: 0},
	{menuBarButtons: 0},
	{gameChange: 0},
	{full_version: 0},
	{webAppUrl: 0},
	{sheet_code: 0},
	{number: 0},
	{total: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	Closer: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	question: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	two: class extends self.ISpriteInstance {},
	company: class extends self.ISpriteInstance {},
	love: class extends self.ISpriteInstance {},
	forUs: class extends self.ISpriteInstance {},
	avanture: class extends self.ISpriteInstance {},
	sex: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	game: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	version2: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	CSVToArray: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	twoArray: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	miss: class extends self.ISpriteInstance {},
	complite: class extends self.ISpriteInstance {},
	reans: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	cardBg: class extends self.ISpriteInstance {},
	numberQuestion: class extends self.ITextInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	buttons: class extends self.ISpriteInstance {},
	menuBarButtons: class extends self.ISpriteInstance {}
}